### ISSUE TITLE
Additional security from tracking through isolating the container from the internet?

### ISSUE THREAD

**Issue by GamePlayer-8** [ngxson/portainer-ce-without-annoying#11]
Good evening,

In the case of Portainer's tracking, they may add tracking at the backend.

Is there any solution to that?

**Comment by erdnuesse** [comment]
Would you care to elaborate? 
Issues based on hypotheticals are pretty much useless for the dev. To make it simple, this sounds like a problem for future-you/us/anyone. 
Also: if it's implemented in their open source edition, the solution would just to remove that portion of the code. As it would be for any unwanted "feature". 

I suggest closing this as unfounded / non-issue.
