### ISSUE TITLE
Cannot use -H command line option 

### ISSUE THREAD

**Issue by joshoram80** [ngxson/portainer-ce-without-annoying#2]
Using the -H command line option does not seem to work.

`node: bad option: -H`

Without this, you can't use a socket-proxy

**Comment by ngxson** [comment]
Yeah you're right, I didn't forward `command` to `/portainer` binary.

Fixed in this commit https://github.com/ngxson/portainer-ce-without-annoying/commit/06278098dc50769aa0caf4042a2b2db22b35c4ea

Please pull the new image from docker hub. Thanks.

**Comment by joshoram80** [comment]
Seems to work fine now. Thanks!
