### ISSUE TITLE
Block tracker

### ISSUE THREAD

**Issue by KeesCBakker** [ngxson/portainer-ce-without-annoying#5]
Hi! Awesome work, this really helps.

I see my adblocker blocking https://cdn.matomo.cloud/portainer-ce.matomo.cloud/matomo.js.

Can we make it a setting that it somehow does not include this JS when tracking is disabled?

Again, awesome job!

**Comment by ngxson** [comment]
Hi, thanks for your suggestion. I surprise to know that such script exists in portainer.

Anw, I added the code to get rid of that script in this PR: https://github.com/ngxson/portainer-ce-without-annoying/pull/6

The `latest` image has been updated. To see if it works or not, check on console log if you see this line: `Blocked insertion of matomo script node`

**Comment by KeesCBakker** [comment]
Super well done! Works like a charm. Thanks for getting it out of there.

**Comment by Barry40** [comment]
Great job, thanks for adding the tracking blocker!

**Comment by Benargee** [comment]
Is this still relevant if you opt out of analytics? https://portal.portainer.io/knowledge/what-information-does-portainer-collect
